[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "strawberry-graphql==0.259.0",
    "typing-extensions>=4.12.2",
    "uvicorn>=0.34.0",
    "files-to-prompt",
]
