/* @generated */
// deno-lint-ignore-file
/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../graphqlContext.ts"
import type { GraphqlBfNode, GraphqlNode } from "./../types/graphqlBfNode.ts"
import type { core, connectionPluginCore } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { count?: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "count"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  RegistrationOptionsAttestationInput: { // input type
    attestationObject: string; // String!
    authenticatorData: string; // String!
    clientDataJSON: string; // String!
    publicKey: string; // String!
    publicKeyAlgorithm: number; // Int!
    transports: NexusGenEnums['RegistrationTransportsFuture'][]; // [RegistrationTransportsFuture!]!
  }
  RegistrationOptionsAuthenticationExtensionsClientOutputs: { // input type
    appid: boolean; // Boolean!
    credProps: NexusGenInputs['RegistrationOptionsCredentialPropertiesOutput']; // RegistrationOptionsCredentialPropertiesOutput!
    hmacCreateSecret: boolean; // Boolean!
  }
  RegistrationOptionsCredentialPropertiesOutput: { // input type
    rk: boolean; // Boolean!
  }
  RegistrationOptionsInput: { // input type
    attestation: NexusGenInputs['RegistrationOptionsAttestationInput']; // RegistrationOptionsAttestationInput!
    authenticatorSelection: string; // String!
    challenge: string; // String!
    clientExtensionResults: NexusGenInputs['RegistrationOptionsAuthenticationExtensionsClientOutputs']; // RegistrationOptionsAuthenticationExtensionsClientOutputs!
    extensions: string; // String!
    id: string; // ID!
    publicKey: string; // String!
    rawId: string; // ID!
    response: NexusGenInputs['RegistrationOptionsAttestationInput']; // RegistrationOptionsAttestationInput!
    supportedAuthenticatorTypes: string; // String!
    timeout: number; // Int!
    type: NexusGenEnums['Thingy']; // Thingy!
    user: string; // String!
  }
}

export interface NexusGenEnums {
  RegistrationTransportsFuture: "ble" | "cable" | "hybrid" | "internal" | "nfc" | "usb"
  Thingy: "public-key"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  BfBlog: { // root type
    id: string; // ID!
    name?: string | null; // String
  }
  BfBlogPost: { // root type
    author?: string | null; // String
    content?: string | null; // String
    cta?: string | null; // String
    id: string; // ID!
    slug?: string | null; // String
    summary?: string | null; // String
    title?: string | null; // String
  }
  BfBlogPostConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfBlogPostEdge'] | null> | null; // [BfBlogPostEdge]
    nodes?: Array<NexusGenRootTypes['BfBlogPost'] | null> | null; // [BfBlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfBlogPostEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfBlogPost'] | null; // BfBlogPost
  }
  BfPerson: { // root type
    id: string; // ID!
    name?: string | null; // String
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  RecommendationItem: { // root type
    confidence?: number | null; // Float
    explanation?: string | null; // String
    recommendedText?: string | null; // String
    sourceText?: string | null; // String
  }
  Recommendations: { // root type
    recommendations?: Array<NexusGenRootTypes['RecommendationItem'] | null> | null; // [RecommendationItem]
  }
  RegistrationOptions: { // root type
    attestation?: string | null; // String
    authenticatorSelection?: string | null; // String
    challenge?: string | null; // String
    extensions?: string | null; // String
    publicKey?: string | null; // String
    supportedAuthenticatorTypes?: string | null; // String
    timeout?: number | null; // Int
    user?: string | null; // String
  }
}

export interface NexusGenInterfaces {
  BfNode: GraphqlBfNode;
  Node: GraphqlNode;
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  BfBlog: { // field return type
    id: string; // ID!
    name: string | null; // String
    posts: NexusGenRootTypes['BfBlogPostConnection'] | null; // BfBlogPostConnection
  }
  BfBlogPost: { // field return type
    author: string | null; // String
    content: string | null; // String
    cta: string | null; // String
    id: string; // ID!
    slug: string | null; // String
    summary: string | null; // String
    title: string | null; // String
  }
  BfBlogPostConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfBlogPostEdge'] | null> | null; // [BfBlogPostEdge]
    nodes: Array<NexusGenRootTypes['BfBlogPost'] | null> | null; // [BfBlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfBlogPostEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfBlogPost'] | null; // BfBlogPost
  }
  BfPerson: { // field return type
    id: string; // ID!
    name: string | null; // String
  }
  Mutation: { // field return type
    qualityCheckTweet: NexusGenRootTypes['Recommendations'] | null; // Recommendations
    register: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    bfNode: NexusGenRootTypes['BfNode'] | null; // BfNode
    blog: NexusGenRootTypes['BfBlog'] | null; // BfBlog
    me: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    registrationOptions: NexusGenRootTypes['RegistrationOptions'] | null; // RegistrationOptions
  }
  RecommendationItem: { // field return type
    confidence: number | null; // Float
    explanation: string | null; // String
    recommendedText: string | null; // String
    sourceText: string | null; // String
  }
  Recommendations: { // field return type
    recommendations: Array<NexusGenRootTypes['RecommendationItem'] | null> | null; // [RecommendationItem]
  }
  RegistrationOptions: { // field return type
    attestation: string | null; // String
    authenticatorSelection: string | null; // String
    challenge: string | null; // String
    extensions: string | null; // String
    publicKey: string | null; // String
    supportedAuthenticatorTypes: string | null; // String
    timeout: number | null; // Int
    user: string | null; // String
  }
  BfNode: { // field return type
    id: string; // ID!
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  BfBlog: { // field return type name
    id: 'ID'
    name: 'String'
    posts: 'BfBlogPostConnection'
  }
  BfBlogPost: { // field return type name
    author: 'String'
    content: 'String'
    cta: 'String'
    id: 'ID'
    slug: 'String'
    summary: 'String'
    title: 'String'
  }
  BfBlogPostConnection: { // field return type name
    count: 'Int'
    edges: 'BfBlogPostEdge'
    nodes: 'BfBlogPost'
    pageInfo: 'PageInfo'
  }
  BfBlogPostEdge: { // field return type name
    cursor: 'String'
    node: 'BfBlogPost'
  }
  BfPerson: { // field return type name
    id: 'ID'
    name: 'String'
  }
  Mutation: { // field return type name
    qualityCheckTweet: 'Recommendations'
    register: 'BfNode'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    bfNode: 'BfNode'
    blog: 'BfBlog'
    me: 'BfPerson'
    registrationOptions: 'RegistrationOptions'
  }
  RecommendationItem: { // field return type name
    confidence: 'Float'
    explanation: 'String'
    recommendedText: 'String'
    sourceText: 'String'
  }
  Recommendations: { // field return type name
    recommendations: 'RecommendationItem'
  }
  RegistrationOptions: { // field return type name
    attestation: 'String'
    authenticatorSelection: 'String'
    challenge: 'String'
    extensions: 'String'
    publicKey: 'String'
    supportedAuthenticatorTypes: 'String'
    timeout: 'Int'
    user: 'String'
  }
  BfNode: { // field return type name
    id: 'ID'
  }
  Node: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  BfBlog: {
    posts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    qualityCheckTweet: { // args
      systemPrompt?: string | null; // String
      taskPrompt?: string | null; // String
      tweet?: string | null; // String
    }
    register: { // args
      registrationInput: NexusGenInputs['RegistrationOptionsInput']; // RegistrationOptionsInput!
    }
  }
  Query: {
    bfNode: { // args
      id?: string | null; // ID
    }
    registrationOptions: { // args
      code: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  BfNode: "BfBlog" | "BfBlogPost" | "BfPerson"
  Node: "BfBlog" | "BfBlogPost" | "BfPerson"
}

export interface NexusGenTypeInterfaces {
  BfBlog: "BfNode" | "Node"
  BfBlogPost: "BfNode" | "Node"
  BfPerson: "BfNode" | "Node"
  BfNode: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}